### ISSUE TITLE
Cannot find module 'artlebedev-typograf'

### ISSUE THREAD

**Issue by VictorKolb** [spat-ne-hochu/artlebedev-typograf#1]
Ничего не работает, после установки npm i node-artlebedev-typograf

**Comment by spat-ne-hochu** [comment]
let typograf = require('node-artlebedev-typograf');

2017-03-27 11:46 GMT+03:00 VictorKolb <notifications@github.com>:

**Comment by VictorKolb** [comment]
Судя по всему нужно обновить readme. Там еще скобка не закрыта в примере инициализации ;-)
